version: "3"
services:
  pg_database:
    image: postgres:11.15-alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=playground
volumes:
  pg_data:
