_format_version: "1.1"
consumers:
- custom_id: my-sas-client-1
  username: anant
plugins:
- config:
    day: null
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: null
    limit_by: consumer
    minute: 3
    month: null
    path: null
    policy: local
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: null
    year: null
  enabled: true
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: mockbin.org
  name: mock
  plugins:
  - config:
      day: null
      fault_tolerant: true
      header_name: null
      hide_client_headers: true
      hour: null
      limit_by: consumer
      minute: 2
      month: null
      path: null
      policy: local
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: null
      year: null
    enabled: true
    name: rate-limiting
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: mocking
    path_handling: v0
    paths:
    - /mock
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: api.qrserver.com
  name: qr
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: qr-routes
    path_handling: v0
    paths:
    - /qr-code
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: reqres.in
  name: weather-services
  path: /
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: names-routes
    path_handling: v0
    paths:
    - /weather
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
