version: "3.3"

services:
  vault-srv:
    container_name: vault-srv
    image: "vault:1.4.2"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
